# Generated by Django 6.0.3 on 2026-03-08 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=100)),
                ('entreprise', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diplome', models.CharField(max_length=150)),
                ('ecole', models.CharField(max_length=100)),
                ('periode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=150)),
                ('presentation', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profil/')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projets/')),
            ],
        ),
        migrations.CreateModel(
            name='Reseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('icone_class', models.CharField(max_length=50)),
                ('lien', models.URLField()),
            ],
        ),
    ]
