# Generated by Django 6.0.3 on 2026-03-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_competence_langue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reseau',
            name='icone_class',
        ),
        migrations.AlterField(
            model_name='reseau',
            name='lien',
            field=models.CharField(max_length=255),
        ),
    ]
