# Generated by Django 6.0.3 on 2026-03-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_reseau_icone_class_alter_reseau_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
    ]
